version: "3"
services:
  naffles-web:
    container_name: naffles-web
    image: naffles-web:dev
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "4001:4001"
    volumes:
      - .:/naffles
      - /naffles/.parcel-cache/
      - /naffles/.yarn/
      - /naffles/dist/
      - /naffles/node_modules/
    tty: true
    stdin_open: true
    command: "dev"
