import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MagicProvider from "../blockchain/context/MagicProvider";
import { UserProvider } from "../blockchain/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        suppressHydrationWarning={true} 
        className={inter.className}
      >
        <MagicProvider>
          <UserProvider>{children}</UserProvider>
        </MagicProvider>
      </body>
    </html>
  );
}
